### ISSUE TITLE
can't submit mount configmap in deployment

### ISSUE THREAD

**Issue by ivanmissu** [kubesphere/kubesphere#5073] opened 2022-07-19 03:15 UTC
**Describe the Bug**
in deployment page, use gui to mount configmap, can't submit.
the submit button is no response.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/8721615/179656671-e55f07c6-1983-4b63-a4fe-a44a8f1e8f52.png)

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
4
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)
CentOS7.9 / 2 master 8/32 / 3nodes 8/32

**Expected behavior**

**Comment by xyz-li** [comment] 2022-07-19 03:38
Duplicate of #5049

**Closed by xyz-li** 2022-07-19 03:38 UTC
Labels: kind/bug
