### ISSUE TITLE
Set Resource Quota stopping deployment 

### ISSUE THREAD

**Issue by WaysonWei** [kubesphere/kubesphere#2564] opened 2020-07-23 09:49 UTC
Set any quota value under project will stop the deployment from app store, no matter the resource request are well below the limited you set. Am I doing anything wrong?

<img width="2556" alt="Screen Shot 2020-07-23 at 9 48 18 PM" src="https://user-images.githubusercontent.com/54336863/88273431-4a7b3680-cd2e-11ea-845f-34544aca8c1e.png">
<img width="2556" alt="Screen Shot 2020-07-23 at 9 47 26 PM" src="https://user-images.githubusercontent.com/54336863/88273444-4f3fea80-cd2e-11ea-8ba0-c3d4fd4bbdbc.png">
<img width="2556" alt="Screen Shot 2020-07-23 at 9 47 16 PM" src="https://user-images.githubusercontent.com/54336863/88273447-50711780-cd2e-11ea-8942-67f8d04a73ce.png">
<img width="2556" alt="Screen Shot 2020-07-23 at 9 45 11 PM" src="https://user-images.githubusercontent.com/54336863/88273450-5109ae00-cd2e-11ea-8580-583e7117d41a.png">

**Comment by zheng1** [comment] 2020-07-25 01:16
I tried to install the chart using the helm command line `helm install my mysql-1.6.6.tgz` and found the same problem, which may be a bug in helm. We will continue to solve this problem

**Comment by rayzhou2017** [comment] 2020-07-29 13:43
what status is the issue?

**Comment by zheng1** [comment] 2020-07-30 14:56
If you set ResourceQuota, then you must specify the `resources requests and limits` of each container when you create the Deployment.
Here is an example:
```bash
root@master:~# kubectl describe resourcequotas -n z1 z1
Name:          z1
Namespace:     z1
Resource       Used  Hard
--------       ----  ----
limits.cpu     0     2
limits.memory  0     4Gi
root@master:~# cat nginx.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: z1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx
    spec:
      containers:
        - name: nginx
          image: 'nginx:1.17.5-alpine'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
root@master:~# kubectl describe replicasets.apps -n z1 nginx  | grep quota | tail -n 1
  Warning  FailedCreate  34s (x8 over 5m59s)  replicaset-controller  (combined from similar events): Error creating: pods "nginx-757f4f4d4-k6tw6" is forbidden: failed quota: z1: must specify limits.cpu,limits.memory
```
MySQL app 1.6.6 [5.7.30] has a bug, **config `requests and limits` in `values.yaml` are not working**. This needs to be fixed by the application developer. 
/assign  @hlwanghl

**Comment by WaysonWei** [comment] 2020-07-31 05:43
yes, that's why I had set the limits in the values.yaml ( default setting without limits ) as the screenshot showed, but still not working.

**Comment by hlwanghl** [comment] 2020-08-04 09:50
It's caused by a UI bug and it was fixed. You can now change default values.yaml and it will work.

Be aware that it will run the test job by default, which doesn't expose `resources` configurations, and don't forget to disable it:

```
testFramework:
  enabled: false
```

Not sure why `helm test` is executed. Maybe @zheng1 can take a look.

**Comment by hlwanghl** [comment] 2020-08-04 09:54
```
testFramework:
  enabled: false

resources:
  limits:
    cpu: "2"
    memory: 2Gi

initContainer:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
```

As it's a convention to not set default `limits` in values.yaml for Helm developers, you should manually set it when the projects have limits set.

**Comment by hlwanghl** [comment] 2020-08-05 09:29
Submitted PR for testFramework issue: https://github.com/helm/charts/pull/23438

**Closed** 2020-08-09 21:56 UTC
Labels: area/app-management, kind/bug, kind/need-to-verify, priority/high
