### ISSUE TITLE
Error occurred during installing helm chart 

### ISSUE THREAD

**Issue by BigFatDog** [kubesphere/kubesphere#1885] opened 2020-02-17 13:20 UTC
**Describe the Bug**
Error occurred during installing helm chart `bitnami/mongodb-sharded`
Always get error `error":"校验失败","code":3` even using chart's default configuration

**Versions Used**
KubeSphere AE v2.0.2
**Environment**
CentOS 7.5 / 1 master:  8cpu/16g; 2 nodes: 8cpu/16g

**How To Reproduce**
1. Go to '平台管理'
2. Click on '添加应用仓库'
3. Wait for dialog open, then input `charts.bitnami.com/bitnami` for repo url.  
4. Keep protocol `https` unchanged
5. Specify name `bitnami` for `应用仓库名称`
6. Click "确认"
7. Click "应用模板"
8. Search chart name `mongodb-sharded`
9. Choose repo name `bitnami` in dropdown menu to make sure the found chart is from the repo that was just added
10. Click the found chart `mongodb-sharded`, which should be `version 1.0.7[4.2.3]`
11. Click "部署应用"
12. Specify `企业空间`, `项目`, `名称`. Choose the latest version of this chart, which is  `version 1.0.7[4.2.3]`. 
13. Click `部署`
14. Get error message `error":"校验失败","code":3`

**Other observations**
1. This bug applies to every version of the chart
2. There is no bug with other chart from the repo `bitnami`. I tried `mongodb` and it works

**Expected behavior**
The chart gets deployed without errors

**Comment by calvinyv** [comment] 2020-02-19 02:22
please make sure if this chart is compatible with current Kubernetes, KubeSphere could only make sure the 9 apps in its integrated default repo could be deployed, but there're thousands of charts outside, their developer may miss testing his app on different K8s

**Comment by BigFatDog** [comment] 2020-02-19 13:56
I don't think this is the right way of doing things.


If you tell me that your team are not willing to support this specific chart or even the entire `bitnami repo`, I'm OK with that.
If you tell me this issue won't be taken care because nobody gets spare time for it, I'm OK with that.
I'm also willing to contribute with some help from your team.

It is all because this is open-source, I value developers' time on it and respect their decisions -- it is based on free will.

However, I'm not OK with the current situation that you, as a maintainer, urge me to perform a time consuming testing **before digging into this issue yourself**.
That's totally unprofessional.

I highly doubt if you really know what it issue is. Currently I can see the error occurred in validation phase, which is before entering deployment. 


If my testing is really required for you to start to resolve this issue. I just close it, give up and move on. I don't appreciate this but I still have love for open-source.

As QingCloud's commercial user, I'll fill a ticket via commercial customer support. If you still think you're doing the right thing, you can 1)claim **only 9 apps** are supported and 2) urge me to do testing again.
I'll guarantee a complaint be filled immediately

PS:
I had checked the requirement of this chart and done testing on my local environment before submitting this issue.

**Comment by rayzhou2017** [comment] 2020-02-19 14:11
I think there is a misunderstanding here.  @calvinyv means there are only nine apps tested for the current KubeSphere releases. He does not mean KubeSphere team won't support other apps from any well-known repo. But it takes time to figure out the problem and mostly like gets fixed in next releases either by KubeSphere development team or by community contributors.

**Comment by rayzhou2017** [comment] 2020-02-19 14:15
@pengcong06 @zheng1 Please take a look at this issue. Thanks.

**Comment by BigFatDog** [comment] 2020-02-19 14:26
> please make sure if this chart is compatible with current Kubernetes

To me that's a clear statement of requiring somebody do something. 
As a developer, the only way that I know is to  *make sure* is to setup a `k8s + helm` environment with exactly the same version as `kubesphere` currently has and then do testing. 

I appreciate your help here, I just keep my original opinions unchanged.

Thank you for your rapid rely and efforts on trying to resolve this issue!

**Comment by zheng1** [comment] 2020-02-19 14:44
![截屏2020-02-1922 40 19](https://user-images.githubusercontent.com/4156721/74844913-283d5100-5369-11ea-9bf4-eab2bcc78359.png)
![截屏2020-02-1922 42 08](https://user-images.githubusercontent.com/4156721/74844925-2d9a9b80-5369-11ea-9c50-661f79fa825d.png)

I think this may be a bug in KubeSphere v2.0.2, I did not reproduce this issue in v2.1.0

**Comment by FeynmanZhou** [comment] 2020-02-19 15:06
@BigFatDog 
This is a bug in KubeSphere v2.0.2, I can deploy this App successfully in KubeSphere 2.1.0. We recommend you to upgrade to 2.1.0, which is much stable and feature-rich.

![image](https://user-images.githubusercontent.com/40452856/74846747-fb3e6d80-536b-11ea-80e5-86e7b1e42b24.png)

![image](https://user-images.githubusercontent.com/40452856/74846832-20cb7700-536c-11ea-8e3b-ccafe1528592.png)

**Comment by BigFatDog** [comment] 2020-02-19 15:42
Got it.
Thank you guys.

**Comment by BigFatDog** [comment] 2020-02-19 16:33
One more question regards with the upgrade. 

I have gone through the [upgrade reference doc](https://kubesphere.io/docs/v2.1/zh-CN/installation/upgrade/). According to the doc, two config files of my current installation are essential for the upgrade:  `conf/hosts.ini` and `conf/vars.yaml`, but I'm not able to find them.

I created k8s cluster via QingCloud's `AppCenter 应用 -> Kubesphere (QKE)应用 -> 创建..`.  Then the cluster was setup with kubesphere automatically without my manual efforts. I looked up in the cluster but couldn't find installation configuration files.

Should I contact qingcloud instead for the upgrade (it seems this is beyond the scope of kubesphere itself) ? Or I missed anything?

**Comment by rayzhou2017** [comment] 2020-02-20 01:49
> One more question regards with the upgrade.
> 
> I have gone through the [upgrade reference doc](https://kubesphere.io/docs/v2.1/zh-CN/installation/upgrade/). According to the doc, two config files of my current installation are essential for the upgrade: `conf/hosts.ini` and `conf/vars.yaml`, but I'm not able to find them.
> 
> I created k8s cluster via QingCloud's `AppCenter 应用 -> Kubesphere (QKE)应用 -> 创建..`. Then the cluster was setup with kubesphere automatically without my manual efforts. I looked up in the cluster but couldn't find installation configuration files.
> 
> Should I contact qingcloud instead for the upgrade (it seems this is beyond the scope of kubesphere itself) ? Or I missed anything?

The file `con/vars.yaml` in **v2.0.2**. was changed to `conf/common.yaml` since **v2.1.0** because we redesigned the installer in order to make it pluggable for cloud providers.

**Comment by rayzhou2017** [comment] 2020-02-20 02:01
> > One more question regards with the upgrade.
> > I have gone through the [upgrade reference doc](https://kubesphere.io/docs/v2.1/zh-CN/installation/upgrade/). According to the doc, two config files of my current installation are essential for the upgrade: `conf/hosts.ini` and `conf/vars.yaml`, but I'm not able to find them.
> > I created k8s cluster via QingCloud's `AppCenter 应用 -> Kubesphere (QKE)应用 -> 创建..`. Then the cluster was setup with kubesphere automatically without my manual efforts. I looked up in the cluster but couldn't find installation configuration files.
> > Should I contact qingcloud instead for the upgrade (it seems this is beyond the scope of kubesphere itself) ? Or I missed anything?
> 
> The file `con/vars.yaml` in **v2.0.2**. was changed to `conf/common.yaml` since **v2.1.0** because we redesigned the installer in order to make it pluggable for cloud providers.

Although QKE is based on KubeSphere, it is different than the open source one. You will find the upgrade button in the console once we publish the new version of QKE, which means you don't need to do anything except click the upgrade button.

**Comment by BigFatDog** [comment] 2020-02-20 02:15
That's all I need.  Thank you so much.

**Closed** 2020-02-20 02:15 UTC
Labels: area/app-management
