### ISSUE TITLE
Edit Persistent Volume Claims storage type error in federation project

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#5183] opened 2022-08-31 09:10 UTC
**Describe the Bug**
1、There is a multi-cluster environment. The host cluster has two storage types: local and csi-qingcloud, and the member cluster has only the local type.
![image](https://user-images.githubusercontent.com/88183150/187639974-3061ba0f-dfd8-4c3c-a180-914a4412bf56.png)

2、There is a federated project multi, a persistent volume declaration test, and the storage class is local.
![image](https://user-images.githubusercontent.com/88183150/187640036-5b42baac-3630-4a73-a21f-a0d6471840ef.png)

3、Edit the persistent volume declaration test and change the storage class to csi-qingcloud, click Save, and the editing is successful
4、Create a federated cluster de, mount the storage volume test, go to the pod details page after creation to view the storage volume information, and the storage type is displayed as local

https://user-images.githubusercontent.com/88183150/187640815-a0ddd897-13a6-47ad-ba68-3a091fe428ca.mp4

**Versions Used**
KubeSphere: v3.3.1-rc.1

/kind bug
/priority medium
/assign @iawia002 @f10atin9

**Comment by iawia002** [comment] 2022-08-31 09:32
The root of the problem is that Federated PVCs should not be allowed to edit information such as storage class, just like regular PVCs, because this information is not allowed to be edited in the first place:

```
Failed to update PersistentVolumeClaim “multi/test” in cluster “host”: PersistentVolumeClaim “test” is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
```

In fact, after you update the Federated PVC it doesn't update the PVC for each cluster (because it can't be updated), resulting in the Pod's PVC still using the local type.

**Comment by wenxin-01** [comment] 2022-09-01 05:49
That is to say, the federated pvc should not set the storage class uniformly when creating and editing, but can set the storage class of each cluster independently. @iawia002 
![image](https://user-images.githubusercontent.com/68640256/187841013-7a9b7cc4-90dc-4a4d-972a-4a8366389b90.png)

**Comment by iawia002** [comment] 2022-09-01 08:51
> the federated pvc should not set the storage class uniformly when creating and editing, but can set the storage class of each cluster independently

Nope, you can't edit PVC after it is created, whether it is federal or general, only capacity can be edited.

> ![image](https://user-images.githubusercontent.com/68640256/187841013-7a9b7cc4-90dc-4a4d-972a-4a8366389b90.png)

Yes, leaves only the capacity section.

**Comment by wenxin-01** [comment] 2022-09-01 10:15
@harrisonliu5 Please cancel 'Storage class' and cancel ’Create‘ button in 'Advanced Settings' tab, in other words, must set storage class in each cluster before pvc created. On the other hand，cancel ’Storage class‘ in 'Edit Settings'.
![image](https://user-images.githubusercontent.com/68640256/187889517-bf69f720-bba0-42d1-9247-e9c5faa6d823.png)
![image](https://user-images.githubusercontent.com/68640256/187889451-570ee913-eb4b-42f5-8e37-a0ec8cd36e5b.png)
 
![image](https://user-images.githubusercontent.com/68640256/187890284-0cfebbf2-678a-4da6-8791-6e80d6074c9d.png)

**Comment by wenxin-01** [comment] 2023-01-17 03:25
Issue fixed in  `kubespheredev/ks-installer:release-3.3`

![image](https://user-images.githubusercontent.com/68640256/212658051-879cff0c-7a20-4674-bbbd-ee9f90f6a871.png)
![image](https://user-images.githubusercontent.com/68640256/212658571-93b369e1-5eb4-4ef3-b99b-e6625b8ff64e.png)

**Closed by wenxin-01** 2023-01-17 03:25 UTC
Labels: kind/bug, kind/need-to-verify
