### ISSUE TITLE
Duplicated Alerting Message shows in history

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3632] opened 2021-03-30 02:49 UTC
**Describe the Bug**
Duplicated Alerting Message shows in history when created a new alert with 'pod abnormal ratio'

**Versions Used**
KubeSphere: nightly-20200328
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
At least 2 nodes exist in Kubernetes clusters.

**How To Reproduce**
1. Go to 'Alerting Policies' and click the 'Create' button
2. On the dialog input the alert name and  click 'Next'
3. Select all the nodes in 'Target Monitoring'
4. Set the 'pod abnormal ratio' as great than 10%. And create it.
5. Check the Alter Messages.  There are 2 same messages shows in the list.
![1617072269(1)](https://user-images.githubusercontent.com/1720333/112925817-0f46c800-9145-11eb-92a3-09dd5958e5d7.png)

**Expected behavior**
Only one Alert message for each Node.

/area alerting
/priority medium
/assign @junotx

**Comment by junotx** [comment] 2021-04-02 08:12
This is caused by that the evaluation of  the recoding rule `node:pod_abnormal:ratio` derives some duplicate metric data, and I am investigating the details.

**Comment by junotx** [comment] 2021-06-10 06:28
@RolandMa1986 This should have been fixed by https://github.com/kubesphere/ks-installer/pull/1475

**Closed** 2021-06-11 03:52 UTC
Labels: area/alerting, priority/medium
