### ISSUE TITLE
when deploy a statfulset, an error occured

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2314] opened 2020-07-06 09:28 UTC
when deploy a statfulset, an error occured.
![image](https://user-images.githubusercontent.com/20178386/86578161-f3dfcf80-bfad-11ea-9eac-6148172db86d.png)

**Comment by leoendless** [comment] 2020-07-07 08:09
Duplicate of https://github.com/kubesphere/console/issues/658

**Closed by leoendless** 2020-07-07 08:09 UTC
Labels: kind/bug
