### ISSUE TITLE
multicluster login failed

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2413] opened 2020-07-14 03:03 UTC
**Describe the Bug**
The multicluster  environment has one host and one member, when login the console of host, it had this error.

![image](https://user-images.githubusercontent.com/53003665/87378837-598d1680-c5c1-11ea-9481-c3fe8c1e5b1c.png)

The ks-apiserver of host has this error 
![image](https://user-images.githubusercontent.com/53003665/87378866-73c6f480-c5c1-11ea-9727-1e70705b3979.png)

The ks-apiserver of member has this error 
![image](https://user-images.githubusercontent.com/53003665/87378883-7de8f300-c5c1-11ea-9093-a7302655e8e9.png)

**Versions Used**
KubeSphere: 3.0.0(2020-07-14)

**Comment by rayzhou2017** [comment] 2020-07-16 09:07
It is caused by the inconsistent secret between host and member. Should be fixed already.

**Closed** 2020-07-17 04:53 UTC
Labels: area/multicluster, kind/need-to-verify
