### ISSUE TITLE
Query the completed status of the task, the query results are incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2506] opened 2020-07-21 01:53 UTC
**Describe the Bug**
there exists tasks with completed status 
Query the completed status of the task, the query result is empty
<img width="915" alt="task" src="https://user-images.githubusercontent.com/36271543/88003571-c4959a80-cb37-11ea-8ee0-d794e4e50ea1.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority high

**Comment by leoendless** [comment] 2020-07-21 02:01
Duplicate of #https://github.com/kubesphere/console/issues/555

**Closed by leoendless** 2020-07-21 02:01 UTC
Labels: area/console, kind/bug, priority/high
