### ISSUE TITLE
devops get pipeline method error

### ISSUE THREAD

**Issue by linkt** [kubesphere/kubesphere#3846] opened 2021-05-07 02:37 UTC
kubesphere version：3.1
I created a pipeline called p1. I made a mistake when editing this pipeline. I found that this  method treats namespace as a pipeline.
![image](https://user-images.githubusercontent.com/7455401/117389533-18367080-af1f-11eb-966b-c56fa2dfe414.png)
![image](https://user-images.githubusercontent.com/7455401/117389966-e07bf880-af1f-11eb-926a-189d03cb341f.png)
![image](https://user-images.githubusercontent.com/7455401/117390118-26d15780-af20-11eb-99bb-5faa8c5834bf.png)

**Comment by LinuxSuRen** [comment] 2021-05-07 02:47
hi @linkt , thanks for reaching out to us.

> I made a mistake when editing this pipeline

I'm not able to reproduce your process. I'm wondering if you can provide more details about this.

/area devops

**Comment by linkt** [comment] 2021-05-07 02:54
@LinuxSuRen  I create a pipeline called p1 ,  the method return the message that Pipeline linkt-testllk6c not found,   but linkt-testllk6c is namespace
![image](https://user-images.githubusercontent.com/7455401/117391456-8d577500-af22-11eb-8be4-812c6384e67c.png)

**Comment by LinuxSuRen** [comment] 2021-05-07 04:02
It works well for me. Please test if it's ok when you create a pipeline with different name?

**Comment by linkt** [comment] 2021-05-07 06:02
@LinuxSuRen The problem has been solved， it is beacuse the controller call jenkins api failed

**Comment by LinuxSuRen** [comment] 2021-05-07 06:03
> the controller call jenkins api failed

Do you still have the error log output? It might be a potential bug.

**Comment by linkt** [comment] 2021-05-08 05:38
@LinuxSuRen The reason is that the address of Jenkins configuration is wrong, and the controller fails to call Jenkins API to create pipeline, but I think this error message should be optimized

**Comment by LinuxSuRen** [comment] 2021-05-08 05:42
> the address of Jenkins configuration is wrong

Thanks for the troubleshooting work. Would you mind tell me where the address configuration is? For example, post the screenshot or CLI output.

**Comment by LinuxSuRen** [comment] 2021-05-17 06:40
> Because I have configured the controller with hostnetwork, the default service name + port is invalid

If I understand correctly, there's a particular issue related to `hostnetwork` configuration. There's no bug here. I guess we can close this issue.

**Comment by LinuxSuRen** [comment] 2021-07-20 10:03
I'll close this issue. You can reopen it if you still have questions about this.
/close

**Closed by LinuxSuRen** 2021-07-20 10:03 UTC
Labels: area/devops
