### ISSUE TITLE
Parts of Pipelines cannot be deleted in KubeSphere DevOps 3.0.0

### ISSUE THREAD

**Issue by ysjjovo** [kubesphere/kubesphere#3938] opened 2021-06-05 02:51 UTC
**Describe the Bug**
I create a lot of pipelines with defualt parameters when debugging kubesphere open-api,each pipeline runs every hour.
Thus lots of pods named 'maven-xxxx' was created,And some of them survival for a long long time,ex. 
![image](https://user-images.githubusercontent.com/4216579/120877655-59877200-c5ea-11eb-92aa-ce0819bb5432.png)
pods status are running and will never stop.Then I try to delete all of the pipeline to solve these problems.
most of pipelines were deleted,but still got some of them exist in the web pages.
![image](https://user-images.githubusercontent.com/4216579/120877800-1548a180-c5eb-11eb-9f65-afcd3e386dba.png)
When I try to delete again,It popups tips 'pipelines.devops.kubesphere.io "pip1" not found'.
I login in to k8s master node.Use cammands filter the 'not exists' pipelines,It doesn't ineed.
![image](https://user-images.githubusercontent.com/4216579/120877865-635da500-c5eb-11eb-94bc-d65d7497c563.png)

**Comment by JohnNiang** [comment] 2021-06-05 03:11
Thanks for your report. Pods named with `maven` prefix are pipeline jobs which are not pipelines. And If you try to delete pipelines in web page manually, you have to wait for a second and refresh pipeline list after deletion.

**Comment by ysjjovo** [comment] 2021-06-05 04:05
> Thanks for your report. Pods named with `maven` prefix are pipeline jobs which are not pipelines. And If you try to delete pipelines in web page manually, you have to wait for a second and refresh pipeline list after deletion.

The problem is that pipelines listed in web page,It doesn't exist in k8s namespace 'kubesphere-devops-system'.Maybe piplines listed in web pages are feteched from other storage other than etcd?

**Comment by JohnNiang** [comment] 2021-06-05 04:30
@ysjjovo I'm sorry that I can't reproduce this issue. Log of ks-apiserver and ks-controller-manager may be helpful for inspecting.

**Comment by LinuxSuRen** [comment] 2021-06-06 09:32
hi @ysjjovo , thanks for reaching out to us. I guess your KubeSphere version is `v3.0.0`. It was fixed in `v3.1.0`.

For your case, please check if those Pipelines exit in Jenkins. Please delete them if you want.

/kind support

**Comment by ysjjovo** [comment] 2021-06-07 00:44
> hi @ysjjovo , thanks for reaching out to us. I guess your KubeSphere version is `v3.0.0`. It was fixed in `v3.1.0`.
> 
> For your case, please check if those Pipelines exit in Jenkins. Please delete them if you want.
> 
> /kind support
> /area devops

Yes, My version is v3.0.0,Thanks a lot！Another problem 'lots of long time running pod' refers to then same bug?Should I make a new Issue?

**Comment by LinuxSuRen** [comment] 2021-06-07 01:09
> Another problem 'lots of long time running pod' refers to then same bug?Should I make a new Issue?

As I mentioned in the last comment.

> For your case, please check if those Pipelines exit in Jenkins. Please delete them if you want.

It might be a bug of the [Jenkins Kubernetes plugin](https://github.com/jenkinsci/kubernetes-plugin) if there's no corresponding Pipeline exist.

In my opinion, it is out of the scope of KubeSphere DevOps. So I'd suggest that we close this issue.

**Comment by LinuxSuRen** [comment] 2021-06-07 01:37
/retitle Parts of Pipelines cannot be deleted in KubeSphere DevOps 3.0.0

**Closed** 2021-06-10 08:17 UTC
Labels: area/devops, kind/support
