### ISSUE TITLE
The TCP traffic data in traffic monitoring is empty

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4498] opened 2021-12-01 08:23 UTC
**Describe the Bug**
1. Set the protocol of the app service to TCP
2. Access the app's services
3. The TCP traffic data in traffic monitoring is empty

![image](https://user-images.githubusercontent.com/36271543/144197757-2da7ff5c-1537-44ad-9acc-714ccf2dabf6.png)

**Versions Used**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @RolandMa1986
/kind bug
/priority Medium

**Comment by RolandMa1986** [comment] 2022-01-18 01:44
It's a front-end issue. The request parameter is incorrect. 

1. When clicking a TCP Service, `filters[]=tcp_sent&filters[]=tcp_received` need to be applied
1.1 Service should only have Inbound data, and `direction=inbound&reporter=source` need to be applied.
Example:
/kapis/servicemesh.kubesphere.io/v1alpha2/namespaces/proj-tcp/services/reviews/metrics?queryTime=1642468764&duration=60&step=120&rateInterval=120s&filters[]=tcp_sent&filters[]=tcp_received&direction=inbound&reporter=source

2. When clicking a TCP Workload, `filters[]=tcp_sent&filters[]=tcp_received` need to be applied
2.1 Inbound, direction=inbound&reporter=source
Example:
/kapis/servicemesh.kubesphere.io/v1alpha2/namespaces/proj-tcp/workloads/reviews-v1/metrics?queryTime=1642468974&duration=60&step=120&rateInterval=120s&filters[]=tcp_sent&filters[]=tcp_received&direction=inbound&reporter=source
2.2 Outbound, `direction=outbound&reporter=source`
Example:
/kapis/servicemesh.kubesphere.io/v1alpha2/namespaces/proj-tcp/workloads/reviews-v1/metrics?queryTime=1642468974&duration=60&step=120&rateInterval=120s&filters[]=tcp_sent&filters[]=tcp_received&byLabels[]=request_protocol&direction=outbound&reporter=source

3. When clicking a HTTP Service, direction=inbound&reporter=destination
example:
/kapis/servicemesh.kubesphere.io/v1alpha2/namespaces/proj1/services/reviews/metrics?queryTime=1642469724&duration=60&step=120&rateInterval=120s&filters[]=request_count&filters[]=request_error_count&byLabels[]=request_protocol&direction=inbound&reporter=destination

4. When clicking a HTTP Service Workload, `direction=inbound&reporter=destination`
example:
/kiali/api/namespaces/proj1/workloads/productpage-v1/metrics?queryTime=1642470024&duration=60&step=120&rateInterval=120s&filters[]=request_count&filters[]=request_error_count&byLabels[]=request_protocol&direction=inbound&reporter=destination

/area console

**Comment by jioce** [comment] 2022-04-13 03:42
problem still exists

1、Deploy the sample application with continuous access to the application
2、View application traffic monitoring
![image](https://user-images.githubusercontent.com/88183150/163095615-f18845b9-257e-42e4-840e-9b30ca36d534.png)

3、productpage service only workload egress traffic monitoring
![image](https://user-images.githubusercontent.com/88183150/163095644-fe9eaee3-1824-40dc-9fc0-a988649e29fa.png)

![image](https://user-images.githubusercontent.com/88183150/163095692-081e5a0e-cd79-4557-a368-e8d80d6da088.png)

![image](https://user-images.githubusercontent.com/88183150/163095710-905779c2-854e-4a25-a9b6-567b9428f679.png)

**Comment by jioce** [comment] 2022-04-28 02:34
issue fixed in v3.3.0-alpha.2

**Comment by wenxin-01** [comment] 2022-05-26 05:45
After restarting kiali, the problem is solved. No way to reproduce the problem has been found for the time being, it is recommended to close the issue for now.

**Closed by wenxin-01** 2022-05-26 05:45 UTC
Labels: kind/bug, area/console, priority/medium

**Comment by hongzhouzi** [comment] 2022-06-17 03:36
The link trace of the gateway needs to be turned on. If you do not turn on the link tracking istio will not be able to collect the data related to the gateway, the traffic entry is here at the gateway, so that the node inbound traffic data can not be collected.
![image](https://user-images.githubusercontent.com/36416216/174219713-774fcc19-5e11-4b48-9421-752bb23b1592.png)

**Comment by jioce** [comment] 2022-06-17 06:18
After gateway link tracking is enabled, traffic monitoring detects data
![image](https://user-images.githubusercontent.com/88183150/174237191-19c35a7c-b840-4d32-b400-3e28cf83cffd.png)

version used 
kubesphere: v3.3.0-rc.2
