### ISSUE TITLE
failed to fetch group version resources types.kubefed.io/v1beta1: the server could not find the requested resource

### ISSUE THREAD

**Issue by githubliuyang777** [kubesphere/kubesphere#5153] opened 2022-08-18 12:36 UTC
华为云CCE K8s Rev: v1.19.10-r1.0.0-source-124
kubesphere Rev: 3.3.0

**Comment by kingcr7** [comment] 2022-09-17 08:12
参考：https://kubesphere.com.cn/forum/d/7610-ks-330-ks-apiserver-crash/6 ，额外手动部署crd资源。感觉是installer漏掉了。

**Comment by benjaminhuo** [comment] 2022-12-28 06:55
We cannot reproduce this in kubesphere v3.3.1, so it's an installation env-related problem, not a KubeSphere defect.
Close it for now

**Closed by benjaminhuo** 2022-12-28 06:55 UTC
Labels: kind/bug
