### ISSUE TITLE
Workspace/App Template，When editing the app template, after uploading the application icon/Screenshots, click Cancel and the uploaded icon will still take effect.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2888] opened 2020-08-18 10:55 UTC
Describe the Bug
App Templates/Audit Records,Operator display error

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Log in with account 'admin'
2.Click 'workbench'
3.Click 'workspaces'
4.click any 'workspace’
5.click 'App Templates'
6.click any 'app template'
7.click 'Edit info'
8.upload the application icon/Screenshots
9.click 'Cancel'

Expected behavior
the uploaded icon/Screenshots does not take effect.
Actual behavior
The uploaded icon/Screenshots will still take effect.

/kind bug
/area console
/assign @leoendless 
/milestone 3.1.0
/priority low

**Comment by leoendless** [comment] 2020-08-18 12:38
Duplicate of #https://github.com/kubesphere/kubesphere/issues/1955

**Closed by leoendless** 2020-08-18 12:38 UTC
Labels: area/console, kind/bug, priority/low
